#!/bin/bash
#----------------------------------------------------------------------------
# This script mounts your remote share with the recommended options.         |
# Just define the remote you wish to mount as well as the local mountpoint.  |
# The script will create a folder at the mountpoint                          |
#----------------------------------------------------------------------------

# Google mountpoint
mntpoint="/mnt/disks/google"

# Remote share
remoteshare="google-cache:"

joined="/mnt/disks/media"

share="/mnt/user/media"

#---------------------------------------------------------------------------------------------------------------------

mkdir -p $mntpoint
mkdir -p $joined
rclone mount --max-read-ahead 1024k --uid=99 --gid=100 --daemon --allow-other $remoteshare $mntpoint
unionfs -o cow,allow_other,uid=99,gid=100 $share=RW:$mntpoint=RO $joined