#!/bin/bash
#----------------------------------------------------------------------------
# This script mounts your remote share with the recommended options.         |
# Just define the remote you wish to mount as well as the local mountpoint.  |
# The script will create a folder at the mountpoint                          |
#----------------------------------------------------------------------------

# Local mountpoint
mntpoint="/mnt/disks/google"     # It's recommended to mount your remote share in /mnt/disks/subfolder -
                                # This is the only way to make it accesible to dockers

# Remote share
remoteshare="google:/Media" 	# If you want to share the root of your remote share you have to
                                # define it as "remote:" eg. "acd:" or "gdrive:" 

joined="/mnt/disks/media"

share="/mnt/user/media"

#---------------------------------------------------------------------------------------------------------------------

mkdir -p $mntpoint
mkdir -p joined
rclone mount --max-read-ahead 1024k --allow-other $remoteshare $mntpoint &
unionfs -o cow,allow_other,uid=99,gid=100 $share=RW:$mntpoint=RO $joined &