#!/bin/bash
#----------------------------------------------------------------------------
# This script unmounts your remote share                                     |
#----------------------------------------------------------------------------

# Local mountpoint
mntpoint="/mnt/disks/google"

#Joined mountpoint
joined="/mnt/disks/media"

							
#---------------------------------------------------------------------------------------------------------------------
umount -l $joined
umount -l $mntpoint
